# Generated by Django 6.0.4 on 2026-04-21 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'managed': True},
        ),
    ]
