# Generated by Django 6.0.4 on 2026-04-21 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=255)),
                ('scan_date', models.DateField()),
                ('scan_password', models.CharField(max_length=255)),
                ('is_active', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(blank=True, db_column='admin_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_schedules', to='accounts.admin')),
            ],
            options={
                'db_table': 'scan_schedules',
                'ordering': ['-id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('masv', models.CharField(max_length=20)),
                ('tensv', models.CharField(max_length=100)),
                ('namsinhsv', models.DateField()),
                ('schedule', models.ForeignKey(blank=True, db_column='schedule_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_histories', to='attendance.scanschedule')),
            ],
            options={
                'db_table': 'scan_histories',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('schedule', 'masv'), name='uq_schedule_masv')],
            },
        ),
    ]
