# Generated by Django 6.0.4 on 2026-04-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('masv', models.CharField(max_length=20)),
                ('tensv', models.CharField(max_length=100)),
                ('namsinhsv', models.DateField()),
            ],
            options={
                'db_table': 'scan_histories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScanSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=255)),
                ('scan_date', models.DateField()),
                ('scan_password', models.CharField(max_length=255)),
                ('is_active', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scan_schedules',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
    ]
